name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: docker pull ghcr.io/ericvilla0896/fastapi-practice:latest

      - name: Restart deployment
        run: |
          cd ~/fastapi-deployment
          docker compose up -d