--
-- PostgreSQL database dump
--

\restrict GfUNCYdhuHfANudgg4cVK2mg6zfRAurjdZ87gt106CAnvqWqfpugkGmUlxmdspz

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6

-- Started on 2026-10-08 14:54:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16385)
-- Name: api_practice_schema; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA api_practice_schema;


--
-- TOC entry 8 (class 2615 OID 16769)
-- Name: rag; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA rag;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16386)
-- Name: analyzed_jobs; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.analyzed_jobs (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    company character varying(200) NOT NULL,
    description text NOT NULL,
    category character varying(100) NOT NULL,
    seniority character varying(50) NOT NULL,
    relevant boolean NOT NULL,
    reason text NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16399)
-- Name: analyzed_jobs_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.analyzed_jobs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME api_practice_schema.analyzed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16400)
-- Name: applications; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.applications (
    id integer NOT NULL,
    company character varying(100) NOT NULL,
    "position" character varying(100) NOT NULL,
    salary integer NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16409)
-- Name: applications_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16410)
-- Name: drug_searches; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.drug_searches (
    id integer NOT NULL,
    product_name character varying NOT NULL,
    suspect_cause character varying NOT NULL,
    effect character varying NOT NULL,
    severity character varying NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16420)
-- Name: drug_searches_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.drug_searches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.drug_searches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16421)
-- Name: webhook_events; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.webhook_events (
    id integer NOT NULL,
    event_id character varying(100) NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 16426)
-- Name: webhook_events_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.webhook_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16825)
-- Name: documents; Type: TABLE; Schema: rag; Owner: -
--

CREATE TABLE rag.documents (
    id integer NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536) NOT NULL,
    source text NOT NULL,
    chunk_id integer NOT NULL,
    page integer NOT NULL,
    content_hash text NOT NULL
);


--
-- TOC entry 230 (class 1259 OID 16824)
-- Name: documents_id_seq; Type: SEQUENCE; Schema: rag; Owner: -
--

CREATE SEQUENCE rag.documents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 230
-- Name: documents_id_seq; Type: SEQUENCE OWNED BY; Schema: rag; Owner: -
--

ALTER SEQUENCE rag.documents_id_seq OWNED BY rag.documents.id;


--
-- TOC entry 3486 (class 2604 OID 16828)
-- Name: documents id; Type: DEFAULT; Schema: rag; Owner: -
--

ALTER TABLE ONLY rag.documents ALTER COLUMN id SET DEFAULT nextval('rag.documents_id_seq'::regclass);


--
-- TOC entry 3488 (class 2606 OID 16428)
-- Name: analyzed_jobs analyzed_jobs_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.analyzed_jobs
    ADD CONSTRAINT analyzed_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3490 (class 2606 OID 16430)
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- TOC entry 3492 (class 2606 OID 16432)
-- Name: drug_searches drug_searches_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.drug_searches
    ADD CONSTRAINT drug_searches_pkey PRIMARY KEY (id);


--
-- TOC entry 3494 (class 2606 OID 16434)
-- Name: webhook_events webhook_events_event_id_key; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.webhook_events
    ADD CONSTRAINT webhook_events_event_id_key UNIQUE (event_id);


--
-- TOC entry 3496 (class 2606 OID 16436)
-- Name: webhook_events webhook_events_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.webhook_events
    ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id);


--
-- TOC entry 3499 (class 2606 OID 16838)
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: rag; Owner: -
--

ALTER TABLE ONLY rag.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- TOC entry 3497 (class 1259 OID 16845)
-- Name: documents_embedding_hnsw_idx; Type: INDEX; Schema: rag; Owner: -
--

CREATE INDEX documents_embedding_hnsw_idx ON rag.documents USING hnsw (embedding public.vector_cosine_ops);


-- Completed on 2026-10-08 14:54:23

--
-- PostgreSQL database dump complete
--

\unrestrict GfUNCYdhuHfANudgg4cVK2mg6zfRAurjdZ87gt106CAnvqWqfpugkGmUlxmdspz

