--
-- PostgreSQL database dump
--

\restrict sZmGvd4CjcHT9KMvUPDbGC6SnRQArfDrXzVihXDwvSRXvv1UWeHZOYriQXLabWq

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-30 18:13:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16389)
-- Name: api_practice_schema; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA api_practice_schema;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 16477)
-- Name: analyzed_jobs; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.analyzed_jobs (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    company character varying(200) NOT NULL,
    description text NOT NULL,
    category character varying(100) NOT NULL,
    seniority character varying(50) NOT NULL,
    relevant boolean NOT NULL,
    reason text NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16476)
-- Name: analyzed_jobs_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.analyzed_jobs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME api_practice_schema.analyzed_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16428)
-- Name: applications; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.applications (
    id integer NOT NULL,
    company character varying(100) NOT NULL,
    "position" character varying(100) NOT NULL,
    salary integer NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 16427)
-- Name: applications_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16461)
-- Name: drug_searches; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.drug_searches (
    id integer NOT NULL,
    product_name character varying NOT NULL,
    suspect_cause character varying NOT NULL,
    effect character varying NOT NULL,
    severity character varying NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16460)
-- Name: drug_searches_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.drug_searches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.drug_searches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16438)
-- Name: webhook_events; Type: TABLE; Schema: api_practice_schema; Owner: -
--

CREATE TABLE api_practice_schema.webhook_events (
    id integer NOT NULL,
    event_id character varying(100) NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16437)
-- Name: webhook_events_id_seq; Type: SEQUENCE; Schema: api_practice_schema; Owner: -
--

ALTER TABLE api_practice_schema.webhook_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME api_practice_schema.webhook_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4837 (class 2606 OID 16491)
-- Name: analyzed_jobs analyzed_jobs_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.analyzed_jobs
    ADD CONSTRAINT analyzed_jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 4829 (class 2606 OID 16436)
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- TOC entry 4835 (class 2606 OID 16472)
-- Name: drug_searches drug_searches_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.drug_searches
    ADD CONSTRAINT drug_searches_pkey PRIMARY KEY (id);


--
-- TOC entry 4831 (class 2606 OID 16446)
-- Name: webhook_events webhook_events_event_id_key; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.webhook_events
    ADD CONSTRAINT webhook_events_event_id_key UNIQUE (event_id);


--
-- TOC entry 4833 (class 2606 OID 16444)
-- Name: webhook_events webhook_events_pkey; Type: CONSTRAINT; Schema: api_practice_schema; Owner: -
--

ALTER TABLE ONLY api_practice_schema.webhook_events
    ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id);


-- Completed on 2026-09-30 18:13:12

--
-- PostgreSQL database dump complete
--

\unrestrict sZmGvd4CjcHT9KMvUPDbGC6SnRQArfDrXzVihXDwvSRXvv1UWeHZOYriQXLabWq

